### ISSUE TITLE
Kafka Listeners must have different Ports 

### ISSUE THREAD

**Issue by twobiers** [The-Microservice-Dungeon/local-dev-environment#6]
Regression from: d224156c04f8894f0bdac1b22cf280111cda0d07

```
kafkabroker  | [2022-01-07 10:11:03,126] ERROR Fatal error during SupportedServerStartable startup. Prepare to shutdown (io.confluent.support.metrics.SupportedKafka)
kafkabroker  | java.lang.IllegalArgumentException: requirement failed: Each listener must have a different port, listeners: INTERNAL://kafka:29092,EXTERNAL_SAME_HOST://localhost:29092
kafkabroker  |  at scala.Predef$.require(Predef.scala:224)
kafkabroker  |  at kafka.utils.CoreUtils$.validate$1(CoreUtils.scala:303)
kafkabroker  |  at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:314)
kafkabroker  |  at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1388)
kafkabroker  |  at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1463)
kafkabroker  |  at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1441)
kafkabroker  |  at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1101)
kafkabroker  |  at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1081)
kafkabroker  |  at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1078)
kafkabroker  |  at kafka.server.KafkaConfig.fromProps(KafkaConfig.scala)
kafkabroker  |  at io.confluent.support.metrics.SupportedServerStartable.<init>(SupportedServerStartable.java:52)
kafkabroker  |  at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:45)
kafkabroker exited with code 1
```

The advertised Listeners need to have different Ports. The Port Mapping needs to be `29092:29092`

**Comment by Valle42** [comment]
Wir haben in Issue https://github.com/The-Microservice-Dungeon/local-dev-environment/issues/7 genau das gleiche festgestellt. Was für ein Zufall :)
